### ISSUE TITLE
Claiming a Meraki device 

### ISSUE THREAD

**Issue by liamkeegan** [cisco-open/terraform-provider-meraki#23] opened 2024-04-30 23:07 UTC
**Prerequisites**
* [X] Have you tested the operation in the API directly? N/A
* [X] Do you have the latest Terraform provider version? Yes
* [X] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Claiming a device generates a Terraform type error: "Error: Value Conversion Error - Cannot use attr.Value basetypes.SetValue, only basetypes.ListValue is supported because basetypes.ListType is the type in the schema
". Same behavior for meraki_organizations_claim and meraki_organizations_inventory_claim resources.

**Expected behavior**
The device would be claimed into the org.

**Screenshots**
N/A

**Environment (please complete the following information):**
* Meraki Dashboard version: No API calls made
* Terraform version:1.8.1
* Meraki provider version: 0.2.0-alpha
* OS Version: MacOS 14.4.1

**Additional context**
Debug log is attached
[inventory_claim_typeerr.log](https://github.com/cisco-open/terraform-provider-meraki/files/15172070/inventory_claim_typeerr.log)

**Comment by liamkeegan** [comment] 2024-05-28 19:26
@fmunozmiranda Thanks for the work on this! 

When I run this block of code, the provider claims the serial number properly, but it returns an error.

```
resource "meraki_organizations_inventory_claim" "acme_org" {

  organization_id = meraki_organizations.acme_org.organization_id
  parameters = {
    serials = ["Q2HN-5LU6-XXXX”]
  }
}
```

Here's the error:
```
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for meraki_organizations_inventory_claim.acme_org.parameters.orders. All values must
│ be known after apply, so this is always a bug in the provider and should be reported in the provider's own repository. Terraform will still save the other
│ known object values in the state.
```
Trace log file attached.

Thanks,

Liam

[tf_claim.txt](https://github.com/cisco-open/terraform-provider-meraki/files/15474934/tf_claim.txt)

**Comment by fmunozmiranda** [comment] 2024-05-30 14:37
@liamkeegan please try it with new version.

**Comment by samspade21** [comment] 2024-05-30 22:37
For me, when trying to claim devices that have already been claimed on the network - I get an error.  Claiming a new serial number works file.  In typical TF style, the way to handle this would be to do a state import reflecting this - however, I am not certain if this resource type supports an import.

**Comment by fmunozmiranda** [comment] 2024-05-31 02:24
Hi no, this is just an action.
<img width="739" alt="image" src="https://github.com/cisco-open/terraform-provider-meraki/assets/93611708/941a6bba-02b8-4038-83d9-cd6175c56cb5">

**Comment by fmunozmiranda** [comment] 2024-05-31 15:36
Closing issue due has the expected behavior.

**Closed by fmunozmiranda** 2024-05-31 15:36 UTC
Labels: in-progress

**Comment by joekohlsdorf** [comment] 2024-10-02 19:30
@fmunozmiranda Can you reopen this please?

The docs say that these are not "entities" but I disagree. The API allows to add devices to the inventory, you can list the inventory and you can release devices from the inventory.
See:
* https://developer.cisco.com/meraki/api-v1/claim-into-organization-inventory/
* https://developer.cisco.com/meraki/api-v1/get-organization-inventory-devices/
* https://developer.cisco.com/meraki/api-v1/release-from-organization-inventory/

Have a look at the provider open sourced by Starbucks, it supports `delete` for both organization and network claims:

* https://github.com/core-infra-svcs/terraform-provider-meraki/blob/main/internal/meraki/networks/devices_claim_resource.go
* https://github.com/core-infra-svcs/terraform-provider-meraki/blob/main/internal/meraki/organizations/claim_resource.go

--- 

There are several similar issues with `meraki_networks_devices_claim` which has the same comment in the docs and `delete` is not implemented.
Here is a simple use case which is to add a new device to an existing network which is not working due to the current limitations.

Apply this:

```
resource "meraki_networks_devices_claim" "this_network_claim_device" {
  network_id = "L_123"
  parameters = {
    serials = ["XXXX-YYYY-ZZZ1", "XXXX-YYYY-ZZZ2",]
  }
}
```

Then try to apply this:

```
resource "meraki_networks_devices_claim" "this_network_claim_device" {
  network_id = "L_123"
  parameters = {
    serials = ["XXXX-YYYY-ZZZ1", "XXXX-YYYY-ZZZ2", "XXXX-YYYY-ZZZ3",]
  }
}
```

My workaround is to claim them one by one but I still can't remove devices from a network through Terraform.
